[package]
name = "zint"
description = "Zink testing utils"
authors.workspace = true
edition.workspace = true
homepage.workspace = true
license.workspace = true
repository.workspace = true
version.workspace = true

[dependencies]
hex.workspace = true
revm-interpreter.workspace = true
revm-primitives.workspace = true
tracing.workspace = true
