[workspace]
members = [
  "abi",
  "cli/*",
  "codegen",
  "compiler",
  "compiler/filetests",
  "evm/opcodes",
  "evm/abi",
  "zink/codegen",
  "zint",
]
resolver = "2"

[workspace.package]
version = "0.1.7"
authors = ["clearloop"]
edition = "2021"
license = "GPL-3.0-only"
homepage = "https://github.com/clearloop/zink"
repository = "https://github.com/clearloop/zink.git"

[workspace.dependencies]
anyhow = "1.0.75"
cargo_metadata = "0.18.1"
clap = "4.4.11"
curl = "0.4.44"
color-eyre = "0.6.2"
colored = "2.1.0"
crates-io = "0.39.0"
etc = "0.1.16"
ethers = "2.0.11"
hex = "0.4.3"
indexmap = "2.1.0"
once_cell = "1.19.0"
parking_lot = "0.12.1"
paste = "1.0.14"
postcard = { version = "1.0.8", default-features = false }
proc-macro2 = "1.0.70"
quote = "1.0.33"
revm = "3.5.0"
semver = "1.0.20"
serde = { version = "1.0.193", default-features = false }
serde_json = "1.0.108"
sha3 = "0.10.8"
smallvec = "1.11.2"
syn =  { version = "2.0.41", features = [ "full" ] }
target-lexicon = "0.12.12"
thiserror = "1.0.51"
tokio = "1.35.0"
toml = "0.8.8"
tracing = "0.1.40"
tracing-subscriber = "0.3.18"
url = "2.5.0"
wasm-opt = "0.116.0"
wasmparser = "0.118.1"
wat = "1.0.82"

# Local packages
ccli = { path = "cli/cli", version = "=0.0.1" }
elko = { path = "cli/elko", version = "=0.1.7" }
opcodes = { package = "evm-opcodes", path = "evm/opcodes", version = "=0.0.3", features = ["data"] }
sol-abi = { path = "evm/abi", version = "=0.0.1" }
zabi = { path = "abi", version = "=0.1.7" }
zingen =  { path = "codegen", version = "=0.1.7" }
zinkc = { path = "compiler", version = "=0.1.7" }
filetests = { package = "zinkc-filetests", path = "compiler/filetests", version = "=0.1.7" }
zink = { path = ".", version = "=0.1.7" }
zink-codegen = { path = "zink/codegen", version = "=0.1.7" }
zint = { path = "zint", version = "=0.1.7" }

[profile]
dev = { panic = "abort"}
release = { panic = "unwind" }

# Zink Programming Language
# -------------------------

[package]
name = "zink"
description = "Standard library for zink projects."
documentation = "https://docs.rs/zink"
version.workspace = true
authors.workspace = true
edition.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true
readme = "zink/README.md"

[lib]
path = "zink/src/lib.rs"

[dependencies]
zink-codegen.workspace = true

[target.'cfg(not(target_arch = "wasm32"))'.dev-dependencies]
anyhow.workspace = true
paste.workspace = true
filetests.workspace = true
zint.workspace = true
tokio = { workspace = true, features = [ "macros" ] }
