[workspace.package]
version = "0.0.0"
authors = ["clearloop"]
edition = "2021"
license = "GPL-3.0-only"

[workspace]
members = [
  "cli",
  "codegen",
  "compiler",
  "examples/*",
  "ir",
  "opcode",
  "runtime",
  "zink",
]
exclude = [
  "examples/.cargo"
]

[workspace.dependencies]
cli = { path = "./cli" }
codegen = { path = "./codegen" }
compiler = { path = "./compiler" }
ir = { path = "./ir" }
opcode = { path = "./opcode" }
runtime = { path = "runtime" }
zink-std = { path = "./std" }
zink = { path = "./zink" }
