[workspace.package]
version = "0.0.0"
authors = ["clearloop"]
edition = "2021"
license = "GPL-3.0-only"

[workspace]
members = [
  "cli",
  "codegen",
  "codegen/opcodes",
  "compiler",
  "examples",
  "zink",
  "zint"
]

[workspace.dependencies]
anyhow = "1.0.71"
cargo_metadata = "0.15.4"
clap = "4.3.10"
color-eyre = "0.6.2"
etc = "0.1.16"
hex = "0.4.3"
paste = "1.0.13"
revm-interpreter = "1.1.2"
revm-primitives = "1.1.2"
smallvec = "1.11.0"
target-lexicon = "0.12.8"
thiserror = "1.0.40"
tracing = "0.1.37"
tracing-subscriber = "0.3.17"
wasmparser = "0.107.0"
wat = "1.0.66"

# Local Dependencies.
cli = { path = "cli" }
opcodes = { package = "evm-opcodes", path = "codegen/opcodes" }
zingen =  { path = "codegen" }
zinkc = { path = "compiler" }
zink = { path = "zink" }
zint = { path = "zint" }

[profile]
dev = { panic = "abort"}
release = { panic = "unwind" }
