[workspace.package]
version = "0.1.4"
authors = ["clearloop"]
edition = "2021"
license = "GPL-3.0-only"
homepage = "https://github.com/clearloop/zink"
repository = "https://github.com/clearloop/zink.git"

[workspace]
members = [
  "cli",
  "codegen",
  "codegen/abi",
  "codegen/opcodes",
  "compiler",
  "utils/*",
  "zink",
  "zink/codegen",
  "zint"
]
resolver = "2"

[workspace.dependencies]
anyhow = "1.0.71"
cargo_metadata = "0.15.4"
clap = "4.3.10"
curl = "0.4.44"
color-eyre = "0.6.2"
colored = "2.0.4"
crates-io = "0.37.0"
etc = "0.1.16"
hex = "0.4.3"
indexmap = "2.0.0"
once_cell = "1.18.0"
parking_lot = "0.12.1"
paste = "1.0.13"
postcard = { version = "1.0.8", default-features = false }
proc-macro2 = "1.0.69"
quote = "1.0.33"
revm = "3.5.0"
semver = "1.0.18"
serde = "1.0.171"
smallvec = "1.11.0"
syn =  { version = "2.0.38", features = [ "full" ] }
target-lexicon = "0.12.8"
thiserror = "1.0.40"
sha3 = "0.10.6"
toml = "0.7.6"
tracing = "0.1.37"
tracing-subscriber = "0.3.17"
wasm-opt = "0.113.0"
wasmparser = "0.107.0"
wat = "1.0.75"

# Local Dependencies.
zabi = { path = "codegen/abi", version = "=0.1.4" }
zinkup = { path = "cli", version = "=0.1.4" }
opcodes = { package = "evm-opcodes", path = "codegen/opcodes", version = "=0.0.3", features = ["data"] }
zingen =  { path = "codegen", version = "=0.1.4" }
zinkc = { path = "compiler", version = "=0.1.4" }
zink = { path = "zink", version = "=0.1.4" }
zink-codegen = { path = "zink/codegen", version = "=0.1.4" }
zint = { path = "zint", version = "=0.1.4" }

[profile]
dev = { panic = "abort"}
release = { panic = "unwind" }
