[workspace.package]
version = "0.0.0"
authors = ["clearloop"]
edition = "2021"
license = "GPL-3.0-only"

[workspace]
members = [
  "cli",
  "codegen",
  "compiler",
  "examples",
  "zink",
  "zink/testing"
]

[workspace.dependencies]
anyhow = "1.0.71"
cargo_metadata = "0.15.4"
clap = "4.3.10"
color-eyre = "0.6.2"
cranelift-wasm = "0.97.1"
cranelift-codegen = "0.97.1"
env_logger = "0.10.0"
etc = "0.1.16"
hex = "0.4.3"
revm-interpreter = "1.1.2"
revm-primitives = "1.1.2"
target-lexicon = "0.12.8"
thiserror = "1.0.40"
wasmtime-environ = "10.0.1"
winch-codegen = "0.8.1"
tracing = "0.1.37"

# Local Dependencies.
cli = { path = "cli" }
zingen =  { path = "codegen" }
zinkc = { path = "compiler" }
zink = { path = "zink" }
zint = { path = "zink/testing" }

[profile]
dev = { panic = "abort"}
release = { panic = "unwind" }
