[workspace]
members = [
  "abi",
  "cli",
  "cli/conta",
  "cli/elko",
  "codegen",
  "codegen/opcodes",
  "compiler",
  "compiler/filetests",
  "sdk",
  "zink/codegen",
  "zint",
]
resolver = "2"

[workspace.package]
version = "0.1.5"
authors = ["clearloop"]
edition = "2021"
license = "GPL-3.0-only"
homepage = "https://github.com/clearloop/zink"
repository = "https://github.com/clearloop/zink.git"

[workspace.dependencies]
anyhow = "1.0.71"
cargo_metadata = "0.15.4"
clap = "4.3.10"
curl = "0.4.44"
color-eyre = "0.6.2"
colored = "2.0.4"
crates-io = "0.37.0"
etc = "0.1.16"
ethers = "2.0.10"
hex = "0.4.3"
indexmap = "2.0.0"
once_cell = "1.18.0"
parking_lot = "0.12.1"
paste = "1.0.13"
postcard = { version = "1.0.8", default-features = false }
proc-macro2 = "1.0.69"
quote = "1.0.33"
revm = "3.5.0"
semver = "1.0.18"
serde = "1.0.171"
sha3 = "0.10.6"
smallvec = "1.11.0"
syn =  { version = "2.0.38", features = [ "full" ] }
target-lexicon = "0.12.8"
thiserror = "1.0.40"
tokio = "1.34.0"
toml = "0.7.6"
tracing = "0.1.37"
tracing-subscriber = "0.3.17"
url = "2.4.1"
wasm-opt = "0.113.0"
wasmparser = "0.107.0"
wat = "1.0.75"

elko = { path = "cli/elko", version = "=0.1.5" }
opcodes = { package = "evm-opcodes", path = "codegen/opcodes", version = "=0.0.3", features = ["data"] }
zabi = { path = "abi", version = "=0.1.5" }
zinkup = { path = "cli", version = "=0.1.5" }
zingen =  { path = "codegen", version = "=0.1.5" }
zinkc = { path = "compiler", version = "=0.1.5" }
zinkc-filetests = { path = "compiler/filetests", version = "=0.1.5" }
zink = { path = ".", version = "=0.1.5" }
zink-codegen = { path = "zink/codegen", version = "=0.1.5" }
zint = { path = "zint", version = "=0.1.5" }

[profile]
dev = { panic = "abort"}
release = { panic = "unwind" }

# Zink Programming Language
# -------------------------

[package]
name = "zink"
description = "Standard library for zink projects."
documentation = "https://docs.rs/zink"
version.workspace = true
authors.workspace = true
edition.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true
readme = "zink/README.md"

[lib]
path = "zink/src/lib.rs"

[dependencies]
zink-codegen.workspace = true

[target.'cfg(not(target_arch = "wasm32"))'.dev-dependencies]
anyhow.workspace = true
paste.workspace = true
zinkc-filetests.workspace = true
zint.workspace = true
