[workspace.package]
version = "0.0.0"
authors = ["clearloop"]
edition = "2021"
license = "GPL-3.0-only"

[workspace]
members = [
  "cli",
  "compiler",
  "runtime",
  "zink",
  "lexer",
  "examples/*"
]

[workspace.dependencies]
hex = "0.4.3"
revm-interpreter = "1.1.2"
revm-primitives = "1.1.2"

# Local Dependencies.
cli = { path = "./cli" }
compiler = { path = "./compiler" }
runtime = { path = "runtime" }
zink-std = { path = "./std" }
zink = { path = "./zink" }

[profile]
dev = { panic = "abort"}
release = { panic = "unwind" }
