[workspace.package]
version = "0.1.3"
authors = ["clearloop"]
edition = "2021"
license = "GPL-3.0-only"
homepage = "https://github.com/clearloop/zink"
repository = "https://github.com/clearloop/zink.git"

[workspace]
members = [
  "cli",
  "codegen",
  "codegen/opcodes",
  "compiler",
  "utils/*",
  "zink",
  "zint"
]
resolver = "2"

[workspace.dependencies]
anyhow = "1.0.71"
cargo_metadata = "0.15.4"
clap = "4.3.10"
color-eyre = "0.6.2"
colored = "2.0.4"
etc = "0.1.16"
hex = "0.4.3"
indexmap = "2.0.0"
paste = "1.0.13"
revm = "3.3.0"
semver = "1.0.18"
serde = "1.0.171"
smallvec = "1.11.0"
target-lexicon = "0.12.8"
thiserror = "1.0.40"
toml = "0.7.6"
tracing = "0.1.37"
tracing-subscriber = "0.3.17"
wasm-opt = "0.113.0"
wasmparser = "0.107.0"
wat = "1.0.66"

# Local Dependencies.
zinkup = { path = "cli", version = "=0.1.3" }
opcodes = { package = "evm-opcodes", path = "codegen/opcodes", version = "=0.0.3", features = ["data"] }
zingen =  { path = "codegen", version = "=0.1.3" }
zinkc = { path = "compiler", version = "=0.1.3" }
zink = { path = "zink", version = "=0.1.3" }
zint = { path = "zint", version = "=0.1.3" }

[profile]
dev = { panic = "abort"}
release = { panic = "unwind" }
