name: "Install conta"
description: "Install conta for publishing packages"

runs:
  using: composite
  steps:
    - uses: actions/checkout@v4
    - uses: dtolnay/rust-toolchain@stable

    - uses: actions/cache@v3
      with:
        path: ~/.cargo/bin/conta
        key: ${{ runner.os }}-conta

    - name: Install Conta
      shell: bash
      run: cargo install conta
