[package]
name = "ztime"
version = "0.0.0"
edition = "2021"
description = "Zink runtime"
license.workspace = true

[dependencies]
hex.workspace = true
revm-interpreter.workspace = true
revm-primitives.workspace = true
