[package]
name = "zinkup"
version = "0.0.0"
edition = "2021"
description = "Zink CLI"
license.workspace = true
homepage = "https://github.com/clearloop/zink"
repository = "https://github.com/clearloop/zink.git"
documentation = "https://docs.rs/zink-cli"

[dependencies]
anyhow.workspace = true
clap = { workspace = true, features = ["derive"] }
zinkc.workspace = true
env_logger.workspace = true
etc.workspace = true
color-eyre.workspace = true
cargo_metadata.workspace = true
tracing.workspace = true
thiserror.workspace = true

[[bin]]
path = "bin/ek.rs"
name = "ek"
