[package]
name = "zinkup"
version.workspace = true
edition.workspace = true
description = "Zink CLI"
license.workspace = true
homepage = "https://github.com/clearloop/zink"
repository = "https://github.com/clearloop/zink.git"
documentation = "https://docs.rs/zink-cli"

[dependencies]
anyhow.workspace = true
cargo_metadata.workspace = true
clap = { workspace = true, features = ["derive"] }
color-eyre.workspace = true
etc.workspace = true
thiserror.workspace = true
tracing.workspace = true
tracing-subscriber = { workspace = true, features = ["std", "env-filter"] }
wasm-opt.workspace = true
zinkc.workspace = true

[[bin]]
path = "bin/elko.rs"
name = "elko"
