[package]
name = "zink-cli"
version = "0.0.0"
edition = "2021"
description = "Zink CLI"
license.workspace = true
homepage = "https://github.com/clearloop/zink"
repository = "https://github.com/clearloop/zink.git"
documentation = "https://docs.rs/zink-cli"

[dependencies]
