[package]
name = "zink-cli"
version = "0.0.0"
edition = "2021"
description = "Zink CLI"
license.workspace = true

[dependencies]
anyhow.workspace = true
clap.workspace = true
zinkc.workspace = true
env_logger.workspace = true
color-eyre.workspace = true
