[package]
name = "zingen"
version = "0.0.0"
edition.workspace = true
license.workspace = true
description = "Code generation library for zink."

[dependencies]
anyhow.workspace = true
cranelift-wasm.workspace = true
cranelift-codegen.workspace = true
wasmtime-environ.workspace = true
target-lexicon.workspace = true
thiserror.workspace = true
winch-codegen.workspace = true
wasmparser.workspace = true
