[package]
name = "zingen"
version = "0.0.0"
edition.workspace = true
license.workspace = true
description = "Code generation library for zink."

[dependencies]
anyhow.workspace = true
opcodes.workspace = true
smallvec.workspace = true
thiserror.workspace = true
tracing.workspace = true
wasmparser.workspace = true
paste.workspace = true
