[package]
name = "zgen"
version = "0.0.0"
edition.workspace = true
license.workspace = true
description = "Code generation library for zink."

[dependencies]
cranelift-wasm.workspace = true
cranelift-codegen.workspace = true
wasmtime-environ.workspace = true
thiserror.workspace = true
