[package]
name = "zingen"
version = "0.0.0"
edition.workspace = true
license.workspace = true
description = "Code generation library for zink."

[dependencies]
anyhow.workspace = true
opcodes.workspace = true
thiserror.workspace = true
wasmtime-environ.workspace = true
wasmparser.workspace = true
