name: Bug Report
description: File a bug report
labels: ["bug"]
body:
    - type: markdown
      attributes:
          value: |
              Please ensure that the bug has not already been filed in the issue tracker.

              Thanks for taking the time to report this bug!
    - type: dropdown
      attributes:
          label: Component
          description: What component is the bug in?
          multiple: true
          options:
              - zuff
              - ztime
              - zinkc
              - zink
              - Other (please describe)
      validations:
          required: true
    - type: input
      attributes:
          label: What version of the component are you on?
          placeholder: "Run `zinkc --version` or get it from the Cargo.lock in your project"
    - type: dropdown
      attributes:
          label: Operating System
          description: What operating system are you on?
          options:
              - Windows
              - macOS (Intel)
              - macOS (Apple Silicon)
              - Linux
    - type: markdown
      attributes:
          value: |
            ### Describe the bug

            <details>
            <summary>Please include the logs as well if relevant.</summary>
            <pre><code>
              <!-- Paste your logs here -->
            </code></pre>
            </details>
      validations:
          required: true
