name: Feature Request
description: Suggest an idea for this project
labels: []
body:
  - type: markdown
    attributes:
      value: |
        Please ensure that the feature has not already been requested in the issue tracker.

        Thanks for helping us improve Zink!
  - type: textarea
    attributes:
      label: Describe the feature
    validations:
      required: true
  - type: textarea
    attributes:
      label: Solution
      description: "Please include the solution as well if it is possible."
