[alias]
bb = "build --all --all-features --release"
be = "build --examples --target wasm32-unknown-unknown --release"
tt = "nextest run --release --all --no-fail-fast"
te = "nextest run --workspace --no-fail-fast --release --examples"
cc = "clippy --all -- -D warnings"
docs = "doc --workspace --document-private-items --all-features --open"
conta = "run --release -p conta"

[target.wasm32-unknown-unknown]
rustflags = [
    "-C", "link-args=--import-memory",
]
