[package]
name = "zinkc"
version = "0.0.1"
edition = "2021"
description = "zink compiler"
license.workspace = true

[dependencies]
anyhow.workspace = true
thiserror.workspace = true
zingen.workspace = true
