[package]
name = "zinkc"
version = "0.0.1"
edition = "2021"
description = "zink compiler"
license.workspace = true

[dependencies]
anyhow.workspace = true
smallvec.workspace = true
thiserror.workspace = true
tracing.workspace = true
wasmparser.workspace = true
zingen.workspace = true

[dev-dependencies]
hex.workspace = true
wat.workspace = true
tracing-subscriber = { workspace = true, features = ["env-filter"]}
zint.workspace = true
