[package]
name = "zinkc"
version = "0.0.0"
edition = "2021"
description = "zink compiler"
license.workspace = true

[dependencies]
anyhow.workspace = true
etc.workspace = true
log.workspace = true
thiserror.workspace = true
cargo_metadata.workspace = true
