[book]
title = "The Zink Language"
authors = ["clearloop"]
multilingual = false
src = "."

[rust]
edition = "2021"

[output.html]
cname = "docs.zink-lang.org"
git-repository-url = "https://github.com/zink-lang/zink"
git-repository-icon = "fa-github"
default-theme = "dark"
preferred-dark-theme = "navy"
curly-quotes = true
mathjax-support = false

# If editable
edit-url-template = "https://github.com/zink-lang/zink/edit/main/docs/{path}"

# If enable folding chapters
[output.html.fold]
enable = true
# level = 1

[output.html.playground]
runnable = false

[output.html.print]
enable = true
page-break = true
