[package]
authors = ["clearloop"]
name = "zint"
version = "0.0.0"
edition = "2021"
description = "Zink testing utils"
license.workspace = true
homepage = "https://github.com/clearloop/zink"
repository = "https://github.com/clearloop/zink.git"
documentation = "https://docs.rs/ztime"

[dependencies]
hex.workspace = true
revm-interpreter.workspace = true
revm-primitives.workspace = true
