name: Release

on:
  workflow_dispatch:
  push:
    tags:
      - "v*"
  pull_request:
    branches: [main]

jobs:
  publish:
    if: github.repository == 'zink-lang/zink'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup rust toolchain
        uses: dtolnay/rust-toolchain@nightly

      - name: Dry run publishing
        run: cargo run --release --bin conta publish --dry-run
        if: ${{ github.ref_name != 'main' }}

      - name: Release packages to crates.io
        run: cargo run --release --bin conta publish
        if: ${{ github.ref_name == 'main' }}
        env:
          CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}
